# Generated by Django 5.2.11 on 2026-04-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_message_attachment_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='推送 Token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='平台')),
                ('device_id', models.CharField(blank=True, default='', max_length=128, verbose_name='设备 ID')),
                ('device_name', models.CharField(blank=True, default='', max_length=120, verbose_name='设备名称')),
                ('app_version', models.CharField(blank=True, default='', max_length=40, verbose_name='App 版本')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='启用推送')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '移动推送设备',
                'verbose_name_plural': '移动推送设备',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='chat_mobile_user_id_b17686_idx'), models.Index(fields=['notifications_enabled'], name='chat_mobile_notific_dacf80_idx')],
            },
        ),
    ]
