# Generated by Django 5.2.11 on 2026-04-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_merge_20260405_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('friends', '仅好友可见'), ('private', '仅自己可见')], default='friends', max_length=20, verbose_name='可见范围')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '朋友圈动态',
                'verbose_name_plural': '朋友圈动态',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '动态评论',
                'verbose_name_plural': '动态评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MomentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moments/%Y/%m/', verbose_name='图片')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='moments/%Y/%m/thumbs/', verbose_name='缩略图')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.moment')),
            ],
            options={
                'verbose_name': '动态图片',
                'verbose_name_plural': '动态图片',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MomentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='moments/videos/%Y/%m/', verbose_name='视频')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='moments/videos/%Y/%m/thumbs/', verbose_name='缩略图')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='视频时长(秒)')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='chat.moment')),
            ],
            options={
                'verbose_name': '动态视频',
                'verbose_name_plural': '动态视频',
            },
        ),
        migrations.CreateModel(
            name='MomentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chat.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '动态点赞',
                'verbose_name_plural': '动态点赞',
                'constraints': [models.UniqueConstraint(fields=('moment', 'user'), name='unique_moment_like')],
            },
        ),
    ]
